version: '2'
services:
  seednode:
    build:
      context: ./
      dockerfile: Dockerfile.seednode
    volumes:
      - ~/.zcash-params:/home/jenkins/.zcash-params
      - ~/.komodo:/home/jenkins/.komodo
      - .:/usr/mm
    env_file:
      - .env.seed
    tty: true
    networks:
      default:
        ipv4_address: 10.100.0.2
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  clientnode:
    build:
      context: ./
      dockerfile: Dockerfile.clientnode
    volumes:
      - ~/.zcash-params:/home/jenkins/.zcash-params
      - ~/.komodo:/home/jenkins/.komodo
      - .:/usr/mm
    links:
      - seednode
    tty: true
    env_file:
      - .env.client
    networks:
      default:
        ipv4_address: 10.100.0.3
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: ./client_debug

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
          gateway: 10.100.0.1