version: '2'
services:
  seednode:
    build:
      context: ./
      dockerfile: Dockerfile.seednode
    volumes:
      - ~/.zcash-params:/home/jenkins/.zcash-params
      - ~/.komodo:/home/jenkins/.komodo
      - .:/usr/mm
    env_file:
      - .env.seed
    tty: true

  clientnode:
    build:
      context: ./
      dockerfile: Dockerfile.clientnode
    volumes:
      - ~/.zcash-params:/home/jenkins/.zcash-params
      - ~/.komodo:/home/jenkins/.komodo
      - .:/usr/mm
    links:
      - seednode
    tty: true
    env_file:
      - .env.client
